# Generated by Django 5.0.6 on 2024-06-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_profilepicture_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='resume',
            field=models.URLField(blank=True),
        ),
    ]
