# Generated by Django 5.0.6 on 2024-06-02 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='rank',
            field=models.IntegerField(default=10),
        ),
    ]
