# Generated by Django 5.0.6 on 2024-06-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_experience_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='tools',
            field=models.TextField(null=True),
        ),
    ]
