# Generated by Django 5.0.6 on 2024-06-15 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_experience_tools'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.TextField()),
                ('languages', models.TextField()),
                ('databases', models.TextField()),
                ('libraries', models.TextField()),
                ('Frameworks', models.TextField()),
                ('tools_and_tech', models.TextField()),
            ],
        ),
    ]
