# Generated by Django 5.0.6 on 2024-06-15 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='Frameworks',
            new_name='frameworks',
        ),
        migrations.AddField(
            model_name='project',
            name='subtitle',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
